target 'Eloquence' do
  platform :osx, '10.11'
  pod "CocoaLumberjack", '~> 2.0'
  pod 'CocoaAsyncSocket', '~> 7.4'
  pod 'CCNPreferencesWindowController', '~> 1.2.2'
  pod 'KeychainSwift', '~> 3.0'
  pod 'KissXML', :git => 'https://github.com/robbiehanson/KissXML.git'
  pod 'XMPPFramework/Core', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/BandwidthMonitor', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/CoreDataStorage', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/FileTransfer', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/GoogleSharedStatus', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/ProcessOne', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/Reconnect', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/Roster', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/SystemInputActivityMonitor', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0009', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0012', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0016', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0045', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0054', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0059', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0060', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0065', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0066', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0077', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0082', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0085', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0092', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0100', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0106', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0115', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0147', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0153', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0172', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0184', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0191', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0198', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0199', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0202', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0203', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0223', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0224', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0280', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0297', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0308', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0333', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0334', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0335', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0352', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0357', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0363', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XMPPMUCLight', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'SwiftyUserDefaults','~> 2.1.3'
  pod 'KSPFetchedResultsController', '~> 1.1.1'
  pod 'JNWCollectionView', :git => 'https://github.com/jwilling/JNWCollectionView.git'
end

target 'EloquenceIOS' do
  platform :ios, '9.0'
  pod "CocoaLumberjack", '~> 2.0'
  pod 'CocoaAsyncSocket', '~> 7.4'
  pod 'KeychainSwift', '~> 3.0'
  pod 'KissXML', :git => 'https://github.com/robbiehanson/KissXML.git'
  pod 'XMPPFramework/Core', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/BandwidthMonitor', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/CoreDataStorage', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/FileTransfer', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/GoogleSharedStatus', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/ProcessOne', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/Reconnect', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/Roster', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/SystemInputActivityMonitor', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0009', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0012', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0016', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0045', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0054', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0059', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0060', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0065', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0066', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0077', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0082', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0085', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0092', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0100', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0106', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0115', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0147', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0153', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0172', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0184', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0191', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0198', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0199', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0202', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0203', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0223', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0224', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0280', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0297', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0308', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0333', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0334', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0335', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0352', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0357', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XEP-0363', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'XMPPFramework/XMPPMUCLight', :git => 'https://github.com/robbiehanson/XMPPFramework.git'
  pod 'ODRefreshControl','~> 1.2'
  pod 'Touchpose','~> 1.2.0'
  pod 'WYPopoverController','~> 0.3.9'
  pod 'SwiftyUserDefaults','~> 2.1.3'
  pod 'SwiftySettings','~> 0.0.3'
  pod 'JSQMessagesViewController','~> 7.2.0'
end

workspace 'Eloquence'
xcodeproj 'Eloquence/Eloquence'
use_frameworks!
